### ISSUE TITLE
PARSE ERORR: Unexpected object operator

### ISSUE THREAD

**Issue by neo4u** [jpapayan/aspis#1]
Hi I was trying to get it working on the same WordPress version (2.9.2) as was in your paper on PHP Aspis and you thesis, but it doesn't seem to be working. I get the following error on the below line:

$this->func_call = "\$db->query(\"$query\")";
// Says that the error is PARSE ERROR: Unexpected T_OBJECT_OPERATOR. Expecting ' " '

Seems to be because of a a parse error to do with a unexpected object operation where an end of string is expected. Does this require extending the grammar or is there some problem with the parser? Could you please point me in the right directions

**Comment by jpapayan** [comment]
Hi neo4u,

So there is one little dirty secret in supporting WP 2.9.2. In order to get it working in time for the paper deadline, I "cheated" a bit. If I remember correctly, I had to change about ~5 lines of WP code to make them more amenable to the rewriting that Aspis performed. Or maybe fewer than 5.

In this particular case, I probably rewrote the function call to `query()` into a separate assignment to a temp variable and then casted the temp variable into a string before assigning it to `$this->func_call`.

Sorry if this caused you lots of trouble. The alternative was for me to spend considerable amount of time to properly support all of PHP's corner cases in regards to inline function calls within double quoted strings. There was no fun in that.

Cheers,
Yiannis

**Comment by neo4u** [comment]
So just to confirm:
`$this->func_call = "\$db->query(\"$query\")";` 
changes to
`$tmp = $db->query("$query");` 
`$this->func_call = (string) $tmp;`

I'm not totally clear on the instructions that you gave?

**Comment by jpapayan** [comment]
Yep. If it doesn't work feel free to experiment more.

**Comment by neo4u** [comment]
Done. Thanks a ton. Got it to work.

```
$this->func_call = "\$db->query(\"$query\")"; 
changes to
$tmp = $db->query("$query");
$this->func_call = (string) $tmp;
```
